apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: delivery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672  # Porta de mensageria
            - containerPort: 15672 # Porta do painel de gestão (UI)
          env:
            # Extrai os valores diretamente do Secret criado anteriormente
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-app-secrets
                  key: rabbitmq_user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: delivery-app-secrets
                  key: rabbitmq_password
          
          # Health checks garantem que a mensageria está pronta antes de os serviços Node ligarem
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 5
            periodSeconds: 5

---
# Serviço de Rede para o RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: delivery-app
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
  type: ClusterIP