apiVersion: v1
kind: Secret
metadata:
  name: delivery-app-secrets
  namespace: delivery-app
type: Opaque
stringData:
  # JWT
  jwt_secret: "ifthispasswordwentonlineifailed"
  
  # Banco de Dados (PostgreSQL)
  postgres_user: "postgres"
  postgres_password: "db#1post"
  postgres_db_delivery: "postgres_db_delivery"
  
  # Mensageria (RabbitMQ)
  rabbitmq_user: "guest"
  rabbitmq_password: "guest"

  #kubectl apply -f secret.yaml

  #kubectl apply -f k8s/infrastructure/
  #kubectl apply -f k8s/apps/

  #kubectl apply -f configmap.yaml
  #kubectl apply -f secret.yaml
  #kubectl apply -f k8s/infrastructure/postgres-deployment.yaml
  #kubectl apply -f k8s/infrastructure/rabbitmq-deployment.yaml