server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Handle client-side routing do Flutter Web
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o Auth Service
    location /api/auth {
        proxy_pass http://auth-service.delivery-app.svc.cluster.local:3001;
    }

    # Proxy para o Restaurant Service
    location /api/restaurants {
        proxy_pass http://restaurant-service.delivery-app.svc.cluster.local:3002;
    }

    # Proxy para o Order Service
    location /api/orders {
        proxy_pass http://order-service.delivery-app.svc.cluster.local:3003;
    }
}